version: "3.8"
services:
  trino:
    image: trinodb/trino
    container_name: trino
    restart: always
    ports:
      - 38080:8080
    volumes:
      - ./trino/config.properties:/etc/trino/config.properties
      - ./trino/jvm.config:/etc/trino/jvm.config
      - ./trino/delta.properties:/etc/trino/catalog/delta.properties
  trino_init:
    image: trinodb/trino
    restart: on-failure
    depends_on:
      - trino
    entrypoint: >
      /bin/sh -ce "
      trino --server trino:8080 --catalog delta --execute \"create schema if not exists delta.default\";
      trino --server trino:8080 --catalog delta --execute \"create table if not exists delta.default.test0 (timestamp BIGINT, date VARCHAR, hour VARCHAR, name VARCHAR, company VARCHAR, score INTEGER) with (location = 's3://test0/', partitioned_by = array['date', 'hour'])\";
      trino --server trino:8080 --catalog delta --execute \"create table if not exists delta.default.test1 (timestamp BIGINT, date VARCHAR, hour VARCHAR, name VARCHAR, company VARCHAR, score INTEGER) with (location = 's3://test1/', partitioned_by = array['date', 'hour'])\";
      exit 0;
      "
