global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 2m

scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 1s
    scrape_timeout: 1s
    static_configs:
      - targets: ["gateway.docker.internal:9100", "172.17.0.1:9100"]
